### ISSUE TITLE
Appears to crash?

### ISSUE THREAD

**Issue by ahepp** [mongoose-examples/raspberry-pi-pico-w#4]
Hello,

This example appears to crash before it can respond to any HTTP requests. 

I see the following serial output:

```
Connected.
2380 2 net.c:139:sfn                    2 SNTP: 1666497620579 ms from epoch
```

And then no more. The device disappears from the connected device list on my wireless access point, I'd estimate less than a minute after it starts running.

`tcpdump` on my router shows the following, where 10.0.0.59 is the pico's DHCP assigned address:
```
03:40:27.889222 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.889258 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.889293 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.906311 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.906346 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.906379 IP 10.0.0.1.67 > 10.0.0.59.68: BOOTP/DHCP, Reply, length 300    
03:40:27.910305 ARP, Request who-has 10.0.0.59 tell 10.0.0.59, length 46        
03:40:27.910305 ARP, Request who-has 10.0.0.59 tell 10.0.0.59, length 46        
03:40:28.921948 ARP, Request who-has 10.0.0.1 tell 10.0.0.59, length 46         
03:40:28.921948 ARP, Request who-has 10.0.0.1 tell 10.0.0.59, length 46         
03:40:28.922122 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:28.922134 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:28.922150 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:29.849199 ARP, Request who-has 10.0.0.1 tell 10.0.0.59, length 46         
03:40:29.849199 ARP, Request who-has 10.0.0.1 tell 10.0.0.59, length 46         
03:40:29.849355 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:29.849367 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:29.849382 ARP, Reply 10.0.0.1 is-at 74:ac:b9:a8:8d:79, length 28          
03:40:29.851280 IP 10.0.0.59.60440 > 8.8.8.8.53: 1+ A? time.google.com. (33)    
03:40:29.851280 IP 10.0.0.59.60440 > 8.8.8.8.53: 1+ A? time.google.com. (33)    
03:40:29.855020 IP 8.8.8.8.53 > 10.0.0.59.60440: 1 4/0/0 A 216.239.35.4, A 216.2
03:40:29.855037 IP 8.8.8.8.53 > 10.0.0.59.60440: 1 4/0/0 A 216.239.35.4, A 216.2
03:40:29.855050 IP 8.8.8.8.53 > 10.0.0.59.60440: 1 4/0/0 A 216.239.35.4, A 216.2
03:40:29.862827 IP 10.0.0.59.60441 > 216.239.35.4.123: NTPv4, Client, length 48 
03:40:29.862827 IP 10.0.0.59.60441 > 216.239.35.4.123: NTPv4, Client, length 48 
03:40:29.929770 IP 216.239.35.4.123 > 10.0.0.59.60441: NTPv4, Server, length 48 
03:40:29.929785 IP 216.239.35.4.123 > 10.0.0.59.60441: NTPv4, Server, length 48 
03:40:29.929799 IP 216.239.35.4.123 > 10.0.0.59.60441: NTPv4, Server, length 48 
03:40:33.119966 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:33.119995 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:33.120017 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:34.143976 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:34.144002 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:34.144018 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:35.167975 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:35.168002 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:40:35.168018 ARP, Request who-has 10.0.0.59 tell 10.0.0.1, length 28         
03:41:12.968345 ARP, Request who-has 10.0.0.59 (ff:ff:ff:ff:ff:ff) tell 0.0.0.0,
03:41:12.968345 ARP, Request who-has 10.0.0.59 (ff:ff:ff:ff:ff:ff) tell 0.0.0.0,
03:41:13.968567 ARP, Request who-has 10.0.0.59 (ff:ff:ff:ff:ff:ff) tell 0.0.0.0 
```

I am not very experienced using a debug probe with FreeRTOS, but when I hooked up my JLink and tried backtracing, I got the following:

```
(gdb) bt
#0  0x10018550 in prvIdleTask ()
#1  0x10017814 in xPortPendSVHandler ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

Although this may not mean anything, since I didn't put any breakpoints into tasks of interest.

It seems possible this is due to my access point, or something in LWIP/FreeRTOS. But I figured I'd ask and see if you've encountered anything like this, or have any ideas about the cause/solutions.

Thanks,
Andrew

**Comment by ahepp** [comment]
I added some `MG_INFO` log statements to net.c and see repeating messages:

```
4ce30 2 net.c:158:device_dashboard_fn   device_dashboard_fn entered
4ce33 2 net.c:224:device_dashboard_fn   device_dashboard_fn exit
```

So I believe I was incorrect about the program crashing. I'm still troubleshooting the failure to connect. I suspect the issue is in some way related to the ARP requests for the PicoW's address, which do not appear to receive a response. Of course, this may be a network configuration issue on my end.

**Comment by ahepp** [comment]
Something strange seems to be happening.

Serial output from the console:

```
Connecting to WiFi...                                                           
Connected.                                                                      
1b9d 2 net.c:158:device_dashboard_fn    device_dashboard_fn entered             
1ba1 2 net.c:160:device_dashboard_fn    ev == MG_EV_OPEN && c->is_listening     
1ba7 2 net.c:224:device_dashboard_fn    device_dashboard_fn exit
1bb7 2 net.c:158:device_dashboard_fn    device_dashboard_fn entered
1bba 2 net.c:224:device_dashboard_fn    device_dashboard_fn exit
1bca 2 net.c:158:device_dashboard_fn    device_dashboard_fn entered
```

Eventually followed by

```
   [380/1975]
235b 2 net.c:158:device_dashboard_fn    device_dashboard_fn entered
235e 2 net.c:224:device_dashboard_fn    device_dashboard_fn exit   
2364 2 net.c:139:sfn                    2 SNTP: 1666844103116 ms from epoch
236b 2 net.c:158:device_dashboard_fn    device_dashboard_fn entered
2370 2 net.c:224:device_dashboard_fn    device_dashboard_fn exit   
```

And more of the same `device_dashboard_fn` polling.

`tcpdump` shows a DHCP transaction, DNS lookup, then NTP query.
<img width="940" alt="Screen Shot 2022-10-26 at 9 17 02 PM" src="https://user-images.githubusercontent.com/7539436/198190381-1e73e549-02de-428a-a317-712b78ffd755.png">

After the NTP query, all that remains are unrequited ARP requests from the router to the Pico W.

The access point logs show:

```
[WLAN access rejected: incorrect security] from MAC address 28:cd:c1:03:2d:a6, Wednesday, October 26, 2022 20:14:58
[Log Cleared] Wednesday, October 26, 2022 20:13:58
```

It appears the Pico may be getting dropped by my access point for "incorrect security". The connection must succeed initially though, as evidenced by the console output and packet capture. I'll continue to investigate.

**Comment by ahepp** [comment]
I have the same issue trying to connect to my wifi via the micropython repl, so it definitely has nothing to do with this project. Sorry for the red herring.
